# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

UNAME_S := $(shell uname -s)
PLATFORM ?= auto

PROJECTS := retrorun

.PHONY: all build clean help sdl2 go2 $(PROJECTS)

# Run a sub-build, preserve its exit status, and always report the elapsed time.
# Usage: $(call timed_build,<make arguments>)
define timed_build
	@start=$$(date +%s); \
	${MAKE} --no-print-directory $(1); \
	status=$$?; \
	end=$$(date +%s); \
	elapsed=$$((end - start)); \
	minutes=$$((elapsed / 60)); \
	seconds=$$((elapsed % 60)); \
	if [ $$status -eq 0 ]; then result="completed"; else result="failed"; fi; \
	printf '==== Build %s in %dm %02ds ====\n' "$$result" "$$minutes" "$$seconds"; \
	exit $$status
endef

all: $(PROJECTS)

# Explicit alias: without a phony target, `make ... build` sees the existing
# build/ directory and incorrectly reports that there is nothing to do.
build: retrorun

ifeq ($(PLATFORM),sdl2)
retrorun:
	@echo "==== Building retrorun SDL2 for Linux/OpenGL ES ===="
	$(call timed_build,-C build/linux-sdl -f Makefile config=$(config))

clean:
	@${MAKE} --no-print-directory -C build/linux-sdl -f Makefile clean
else ifeq ($(PLATFORM),go2)
retrorun:
	@echo "==== Building retrorun GO2/DRM ($(config)) ===="
	$(call timed_build,-C build/gmake -f Makefile)

clean:
	@${MAKE} --no-print-directory -C build/gmake -f Makefile clean
else ifeq ($(UNAME_S),Darwin)
retrorun:
	@echo "==== Building retrorun SDL2 for macOS ===="
	$(call timed_build,-C build/macos -f Makefile)

clean:
	@${MAKE} --no-print-directory -C build/macos -f Makefile clean
else
retrorun: 
	@echo "==== Building retrorun ($(config)) ===="
	$(call timed_build,-C build/gmake -f Makefile)

clean:
	@${MAKE} --no-print-directory -C build/gmake -f Makefile clean
endif

sdl2:
	@${MAKE} --no-print-directory PLATFORM=sdl2 config=$(config) retrorun

go2:
	@${MAKE} --no-print-directory PLATFORM=go2 config=$(config) retrorun

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   retrorun"
	@echo "   sdl2       Linux SDL2/KMSDRM/OpenGL ES alternative"
	@echo "   go2        Native GO2/DRM backend (Linux default)"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
